In [3]:
import pandas as pd

df_mun = pd.read_csv('FinalData/all_data_mun.csv')
df_mun

,Municipality,Region,year,purchase_price_mean,purchase_price_median,sqm_price_mean,sqm_price_median,sqm_mean,no_rooms_mean,%_change_between_offer_and_purchase_mean,nom_interest_rate%_mean,dk_ann_infl_rate%_mean,yield_on_mortgage_credit_bonds%_mean,no_sales,income,population
0,Aabenraa,Southern Denmark,2008,1.631118e+06,1065000.0,12842.465,8209.458984,142.541760,4.691649,-1.708779,4.046039,3.420000,6.52,467,276912.666667,60316.75
1,Aabenraa,Southern Denmark,2009,1.535254e+06,1025000.0,11637.358,8295.454102,147.158040,4.762943,-2.779292,1.916621,1.300000,5.50,367,278411.000000,60237.00
2,Aabenraa,Southern Denmark,2010,1.577195e+06,1140000.0,12633.355,8218.090332,143.672870,4.609665,-3.046469,0.795074,2.310000,4.53,538,301608.000000,59946.00
3,Aabenraa,Southern Denmark,2011,1.499740e+06,1000000.0,11417.911,7557.471191,142.918910,4.621622,-3.075075,1.002252,2.760000,4.75,333,305809.000000,59750.00
4,Aabenraa,Southern Denmark,2012,1.564110e+06,1070119.5,12550.895,7907.049072,142.817500,4.585000,-3.737500,0.420625,2.400000,3.66,400,312566.666667,59457.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661,Ærø,Southern Denmark,2020,1.093633e+06,850000.0,9406.151,7468.750000,126.863434,4.295154,-3.788546,0.000000,0.420000,1.10,227,336656.333333,5970.00
1662,Ærø,Southern Denmark,2021,1.245801e+06,920000.0,11591.367,8251.983887,126.557144,4.389286,-2.392857,0.000000,1.850000,1.47,280,349446.333333,5998.00
1663,Ærø,Southern Denmark,2022,1.209536e+06,950000.0,10318.044,8041.322266,126.802030,4.456853,-2.786802,0.128680,7.699999,3.73,197,347889.666667,6039.25
1664,Ærø,Southern Denmark,2023,1.187258e+06,950000.0,9634.060,8378.377930,130.212900,4.554839,-3.219355,2.800645,3.310000,4.79,155,356355.666667,6003.75
1665,Ærø,Southern Denmark,2024,1.229129e+06,1012500.0,10421.465,8578.211426,129.143830,4.602740,-3.493151,3.507534,1.130000,4.34,146,366094.000000,5937.50

In [5]:
df_reg = pd.read_csv('FinalData/all_data_reg.csv')
df_reg

,Region,year,purchase_price_mean,purchase_price_median,sqm_price_mean,sqm_price_median,sqm_mean,no_rooms_mean,%_change_between_offer_and_purchase_mean,nom_interest_rate%_mean,dk_ann_infl_rate%_mean,yield_on_mortgage_credit_bonds%_mean,no_sales,income,population
0,Capital Region,2008,2.682002e+06,2434331.0,22303.014,21229.114258,122.660730,4.255962,-4.220502,4.045254,3.42,6.52,6458,328484.885057,1138804.50
1,Capital Region,2009,2.455395e+06,2100000.0,19447.010,17916.666016,126.134780,4.346792,-5.640264,1.793697,1.30,5.50,7108,328673.494253,1146752.50
2,Capital Region,2010,2.599042e+06,2295000.0,20469.210,19166.666016,127.998350,4.354061,-3.741690,0.807258,2.31,4.53,9086,364020.459770,1155271.50
3,Capital Region,2011,2.557964e+06,2195000.0,20362.146,18852.458984,125.445970,4.267731,-4.498824,0.989448,2.76,4.75,8079,373740.356322,1161875.00
4,Capital Region,2012,2.513142e+06,2175000.0,20137.494,18750.000000,125.935330,4.271355,-4.424484,0.421313,2.40,3.66,9541,383552.574713,1168063.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Zealand Region,2020,1.823485e+06,1450000.0,15783.636,13333.333008,121.782196,4.225827,-2.458933,0.000000,0.42,1.10,17447,411127.803922,837636.75
81,Zealand Region,2021,2.067815e+06,1655000.0,17442.950,14784.946289,125.793846,4.275750,-1.510686,0.000000,1.85,1.47,19699,429899.627451,840704.75
82,Zealand Region,2022,2.057488e+06,1650000.0,17686.943,14925.373047,123.072790,4.219778,-2.820344,0.118957,7.70,3.73,13409,431623.352941,846588.75
83,Zealand Region,2023,2.011127e+06,1600000.0,17421.045,14830.508789,121.576180,4.225845,-3.484734,2.834010,3.31,4.79,13527,447318.470588,850802.25
84,Zealand Region,2024,2.080557e+06,1650000.0,17995.002,15509.258789,121.788246,4.225766,-3.433652,3.512342,1.13,4.34,10347,458730.392157,853605.25